from app.schemas import ma
from marshmallow import fields

#Define customer Schema
class UserSchema(ma.Schema):
    id = fields.Integer(required=False) #is is autogenerated
    first_name = fields.String(required=True)
    last_name = fields.String(required=True)
    username = fields.String(required=True)
    # email  = fields.String(required=True)
    password = fields.String(required=True)
    checkings = fields.String(required=True)
    savings = fields.String(required =True)
    budget = fields.String(required=True)
    goals = fields.String(required=True)

#user instances of the schema
user_input_schema = UserSchema()
user_output_schema = UserSchema(exclude=["password"])
users_schema = UserSchema(many=True, exclude=["password"])