"""empty message

Revision ID: a55e166e84e6
Revises: efcab1e83d2c
Create Date: 2024-08-29 01:04:59.954163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55e166e84e6'
down_revision = 'efcab1e83d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkings', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('savings', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('budget', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('goals', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('goals')
        batch_op.drop_column('budget')
        batch_op.drop_column('savings')
        batch_op.drop_column('checkings')

    # ### end Alembic commands ###
